kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: orion-platform
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 9001
    hostPort: 9001
    protocol: TCP
  - containerPort: 5432
    hostPort: 5432
    protocol: TCP
